# version: "3"
services:
  server:
    build:
      context: ./my-special-shop
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["bash", "./scripts/entrypoint.sh"]
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vendure
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - database
  worker:
    build:
      context: ./my-special-shop
      dockerfile: Dockerfile
    command: ["npm", "run", "start:worker"]
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vendure
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - server
  notification:
    build:
      context: ./novu-notification/my-novu-app
      dockerfile: Dockerfile.server
    ports:
      - 4000:4000
    command: ["sh", "./scripts/on-docker.sh"]
    volumes:
      - /usr/src/app
  client:
    build:
      context: ./storefront-angular-starter
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - /usr/src/app
  database:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure
